/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CardsCardIdImport } from './routes/cards.$cardId'

// Create Virtual Routes

const CardsLazyImport = createFileRoute('/cards')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const CardsLazyRoute = CardsLazyImport.update({
  path: '/cards',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cards.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CardsCardIdRoute = CardsCardIdImport.update({
  path: '/$cardId',
  getParentRoute: () => CardsLazyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cards': {
      preLoaderRoute: typeof CardsLazyImport
      parentRoute: typeof rootRoute
    }
    '/cards/$cardId': {
      preLoaderRoute: typeof CardsCardIdImport
      parentRoute: typeof CardsLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CardsLazyRoute.addChildren([CardsCardIdRoute]),
])

/* prettier-ignore-end */
